name: Build and deploy Python project to Azure Function App - diet-function

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38C1805A84A942338BEF81DDE6F7A263 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3636B9BD957549B38F210D90F916F740 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4B306D9F70DC4BAF85E1D9283F32C47C }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'diet-function'
          package: ./backend
          scm-do-build-during-deployment: true #forces Python build system
          enable-oryx-build: true #installs requirements.txt